CeLaFaremoMVC/Models/Electronic.cs
using CeLaFaremoMVC.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CeLaFaremoMVC.Models
{
    public class Electronic
    {
        [Key] 
        public int Id { get; set; }
        public Categories Category { get; set; }
        public List<Laptop> Laptops { get; set; }
        public List<Phone> Phones { get; set; }
    }
}

CeLaFaremoMVC/Models/Laptop.cs
using CeLaFaremoMVC.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CeLaFaremoMVC.Models
{
    public class Laptop
    {
        [Key] 
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Modello { get; set; }
        public int RamMemory { get; set; }
        public int SsdMemory { get; set; }
        public int ElectronicId { get; set; }
    }
}

CeLaFaremoMVC/Models/Phone.cs
using CeLaFaremoMVC.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CeLaFaremoMVC.Models
{
    public class Phone
    {
        [Key] 
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Categories Categories { get; set; }
        public int ElectronicId { get; set; }
    }
}

CeLaFaremoMVC/Controllers/ElectronicController.cs
using CeLaFaremoMVC.Data;
using CeLaFaremoMVC.Enums;
using CeLaFaremoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CeLaFaremoMVC.Controllers
{
    public class ElectronicController : Controller
    {
        // per ottenere i nostri dati dal database e poi mostrarli tramite le View
        // dobbiamo passare dal controller usando la dependency injection

        // iniziamo scrivendo un private ApplicationDbContext chiamato _db
        private readonly ApplicationDbContext _db;

        // ora abbiamo bisogno di un costruttore dove poi prenderemo il database context
        public ElectronicController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET LIST
        public IActionResult Index()
        {
            IEnumerable<Electronic> objList = _db.Electronics;

            return View(objList);
        }

        // con questa view io dopo il click su Create vado a far mostrare la pagina con il form del Create
        // ma non vado ad effettuare la Post... quindi qui non va nessun httpPost ie-KTM
        // Get Create Electronic Form / Page Form

        // GET CREATE
        public IActionResult Create()
        {
            return View();
        }

        // POST CREATE
        [HttpPost]
        public IActionResult Create(Electronic obj, Categories cat)
        {
            _db.Electronics.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Electronics.Find(id);
            if (obj == null)
            {
                return NotFound();
            }   
            return View(obj);
        }

        // POST DELETE
        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Electronics.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Electronics.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET UPDATE
        public IActionResult Update(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var obj = _db.Electronics.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // POST UPDATE
        [HttpPost]
        public IActionResult UpdatePost(Electronic obj)
        {
            if (ModelState.IsValid)
            {
                _db.Electronics.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

CeLaFaremoMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CeLaFaremoMVC.Controllers
{
    public class HomeController : Controller
    { 
        public IActionResult Index()
        {
            return View();
        }
    }
}

CeLaFaremoMVC/Controllers/LaptopController.cs
using CeLaFaremoMVC.Data;
using CeLaFaremoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CeLaFaremoMVC.Controllers
{
    public class LaptopController : Controller
    {
        // il controller una volta ricevuta una richiesta a chi si deve collegare?
        // quindi andiamo a collegarci al Data/DbContext
        private readonly ApplicationDbContext _db;

        // quindi una volta che abbiamo letto il dbcontext
        // facciamo u costruttore vuoto per collegarci al db
        // questo db poi lo useremo per collegarci alla "tabella" che vogliamo del nostro database
        public LaptopController(ApplicationDbContext db)
        { 
            _db = db;
        }

        public IActionResult Index()
        {
            // quindi andiamo a prendere la collection delle proprieta' della nostra classe che vogliamo usare qui
            IEnumerable<Laptop> objList = _db.Laptops;
            return View(objList);
        }

        // GET CREATE
        public IActionResult Create()
        {
            return View();
        }

        // POST CREATE
        [HttpPost]
        public IActionResult Create(Laptop obj)
        {
            _db.Laptops.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Laptops.Find(id);
            if (obj == null)
            {
                return NotFound();
            };
            return View(obj);
        }

        // POST DELETE
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Laptops.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Laptops.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET UPDATE
        public IActionResult Update(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var obj = _db.Laptops.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // POST UPDATE
        public IActionResult UpdatePost(Laptop obj)
        {
            if (ModelState.IsValid)
            {
                _db.Laptops.Update(obj);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

CeLaFaremoMVC/Views/Electronic/Create.cshtml
@model CeLaFaremoMVC.Models.Electronic
@using CeLaFaremoMVC.Enums

@{
    ViewData["Title"] = "Create Electronic";
}
<h2 style="color:yellow ;text-align:center">ENTER THE DATA</h2>
<br />
<form method="post" asp-controller="Electronic" asp-action="Create">

    @*l'anchor serve proprio per trasferici poi su un'altra pagina
        <a>: The Anchor element. The <a> HTML element (or anchor element), with its href attribute,
        creates a hyperlink to web pages, files, email addresses, locations in the same page,
        or anything else a URL can address. Content within each <a> should indicate the link's destination.*@
    <table class="table table-bordered table-striped" style="width:auto; margin-left: auto;margin-right: auto; width:30%">
        <tr>
            <td style="text-align:center">
                <label asp-for="Category" style="color:red">Category</label>
                @*asp-for serve per dire che voglio fare questo post in modo specifico per questa proprieta'*@
                @*Il tag HTML <span> è utilizzato per raggruppare e applicare stili ad elementi inline.*@
                <select
                        asp-for="Category" asp-items="Html.GetEnumSelectList<Categories>()" style="float:right; width:189px">
                    <option>Choose the Category</option>
                </select>
                <span asp-validation-for="Category"></span>
            </td>
        </tr>
    </table>
    <div style="text-align:center">
        <input type="submit" value="Create" class="btn btn-danger" width="65" />
        <a asp-controller="Electronic" asp-action="Index" class="btn btn-success" style="margin-left:5px">Go Back</a>
    </div>
</form>

CeLaFaremoMVC/Views/Electronic/Delete.cshtml
@model CeLaFaremoMVC.Models.Electronic

@{
    ViewData["Title"] = "Delete Electronic";
}
<h2 style="color:yellow ;text-align:center">ARE YOU SURE???</h2>
<br />
<form method="post" asp-controller="Electronic" asp-action="DeletePost" asp-route-Id="@Model.Id">

    @*l'anchor serve proprio per trasferici poi su un'altra pagina
        <a>: The Anchor element. The <a> HTML element (or anchor element), with its href attribute,
        creates a hyperlink to web pages, files, email addresses, locations in the same page,
        or anything else a URL can address. Content within each <a> should indicate the link's destination.*@
    <table class="table table-bordered table-striped" style="width:auto; margin-left: auto;margin-right: auto; width:30%">
        <thead style="text-align:center">
            <tr>
                <td text-align:center">
                    <label asp-for="Id" style="color:red;">Id</label>
                    @*asp-for serve per dire che voglio fare questo post in modo specifico per questa proprieta'*@
                    <input asp-for="Id" placeholder="Insert the Id..." style="float:right" disabled />
                </td>
            </tr>
        </thead>
        <tr>
            <td style="text-align:center">
                <label asp-for="Category" style="color:red">Category</label>
                @*asp-for serve per dire che voglio fare questo post in modo specifico per questa proprieta'*@
                @*Il tag HTML <span> è utilizzato per raggruppare e applicare stili ad elementi inline.*@
                <input asp-for="Category" placeholder="Category..." style="float:right" disabled/>
            </td>
        </tr>
    </table>
    <div style="text-align:center">
        <input type="submit" value="Delete" class="btn btn-danger" width="65" />
        <a asp-controller="Electronic" asp-action="Index" class="btn btn-success" style="margin-left:5px">Go Back</a>
    </div>
</form>

CeLaFaremoMVC/Views/Electronic/Index.cshtml
@model IEnumerable<CeLaFaremoMVC.Models.Electronic>

@{
    ViewData["Title"] = "Electronic Index";
}

@*questo model count qui sotto ci serve per dire che se abbiamo piu di 0 elementi da mostrare
    li faremo vedere
    altrimenti diremo che non abbiamo nulla in questa pagina, in modo specifico non abbiamo cose nella tabella di questo db*@
@if (Model.Count() > 0)
{
    <h1 style="text-align:center">LIST OF ELECTRONIC STUFF</h1>
    <br />
    @*The <div> tag defines a division or a section in an HTML document*@
    <div class="container">
        <table class="table table-bordered table-striped" style="width:auto; margin-left: auto;margin-right: auto;">
            @*The <thead> tag is used to group header content in an HTML table*@
            <thread>
                <tr>
                    @* tr => table row => riga*@
                    <td id="headTextColor">
                        @*td => table data*@
                        Category Id
                    </td>
                    <td id="headTextColor">
                        Category
                    </td>
                    <td id="headTextColor">
                        Modify or Delete
                    </td>
                </tr>
            </thread>
            <tbody>
                @*The <tbody> tag is used to group the body content in an HTML table*@
                @foreach (var electronic in Model)
                {
                    <tr style="text-align:center">
                        <td width="35%">@electronic.Id</td>
                        <td width="35%">@electronic.Category</td>
                        <td width="30%">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="Electronic" asp-action="Update" asp-route-Id="@electronic.Id" class="btn btn-success mx-1">Modify</a>
                                <a asp-controller="Electronic" asp-action="Delete" asp-route-Id="@electronic.Id" class="btn btn-danger mx-1">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
                @*l'anchor serve proprio per trasferici poi su un'altra pagina
                    <a>: The Anchor element. The <a> HTML element (or anchor element), with its href attribute,
                        creates a hyperlink to web pages, files, email addresses, locations in the same page,
                        or anything else a URL can address. Content within each <a> should indicate the link's destination.*@

                @*con questo a (che sarebbe un anchor) lo uso per creare un bottone che una volta cliccato mi porta alla mia pagina
                    tramite la action create*@
                @*mx-1 mi serve per creare spazio tra i buttons*@

            </tbody>
        </table>
    </div>
}
else
{
    <br />
    <div style="text-align:center">
        <h1>
            <i class="fas fa-user-astronaut" style="color:greenyellow"></i>
            <a id="aHover" href="https://i.kym-cdn.com/entries/icons/original/000/027/100/_103330503_musk3.jpg">WARNING</a>
            <i class="fas fa-space-shuttle" style="color:red"></i>
        </h1>
        <p>
            <h2>Elon Muskio has stolen your List of Object</h2>
        </p>
        <h2>so...</h2>
        <p>
            <h3 style="color:yellow">there is no argument in this section!</h3>
        </p>
        <p>
            <h2>but...</h2>
        </p>
        <p>
            <h4 style="color:greenyellow">You can create a new Electronic Field,</h4>
        </p>
        <p>
            <h4 style="color:white">
                <i class="fas fa-hand-point-down" style="color:greenyellow"></i>
                click on the button below
                <i class="fas fa-hand-point-down" style="color:red"></i>
            </h4>
        </p>
    </div>
    <br />
}
<div style="text-align:center">
    @*l'anchor serve proprio per trasferici poi su un'altra pagina
        <a>: The Anchor element. The <a> HTML element (or anchor element), with its href attribute,
            creates a hyperlink to web pages, files, email addresses, locations in the same page,
            or anything else a URL can address. Content within each <a> should indicate the link's destination.*@

    @*con questo a (che sarebbe un anchor) lo uso per creare un bottone che una volta cliccato mi porta alla mia pagina
        tramite la action create*@
    <a id="btnCreate" class="btn btn-danger" asp-controller="Electronic" asp-action="Create">Create a New Electronic Field</a>
</div>

CeLaFaremoMVC/Views/Electronic/Update.cshtml
@model CeLaFaremoMVC.Models.Electronic
@using CeLaFaremoMVC.Enums 

@{
    ViewData["Title"] = "Update Electronic";
}
<h2 style="color:yellow ;text-align:center">INSERT THE DATA</h2>
<br />
<form method="post" asp-controller="Electronic" asp-action="UpdatePost" asp-route-Id="@Model.Id">

    @*l'anchor serve proprio per trasferici poi su un'altra pagina
        <a>: The Anchor element. The <a> HTML element (or anchor element), with its href attribute,
        creates a hyperlink to web pages, files, email addresses, locations in the same page,
        or anything else a URL can address. Content within each <a> should indicate the link's destination.*@
    <table class="table table-bordered table-striped" style="width:auto; margin-left: auto;margin-right: auto; width:30%">
        <thead style="text-align:center">
            <tr>
                <td text-align:center">
                    <label asp-for="Id" style="color:red;">Id</label>
                    @*asp-for serve per dire che voglio fare questo post in modo specifico per questa proprieta'*@
                    <input asp-for="Id" placeholder="Insert the Id..." style="float:right" disabled />
                    <span asp-validation-for="Id"></span>
                </td>
            </tr>
        </thead>
        <tr>
            <td style="text-align:center">
                <label asp-for="Category" style="color:red">Category</label>
                @*asp-for serve per dire che voglio fare questo post in modo specifico per questa proprieta'*@
                @*Il tag HTML <span> è utilizzato per raggruppare e applicare stili ad elementi inline.*@
                <select asp-for="Category" asp-items="Html.GetEnumSelectList<Categories>()"  style="float: right; width: 189px">
                    <option>Choose a Category</option>
                </select>
                <span asp-validation-for="Category"></span>
            </td>
        </tr>
    </table>
    <div style="text-align:center">
        <input type="submit" value="Update" class="btn btn-danger" width="65" />
        <a asp-controller="Electronic" asp-action="Index" class="btn btn-success" style="margin-left:5px">Go Back</a>
    </div>
</form>

CeLaFaremoMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "HomePage";
}

<br />
<div style="text-align:center; color:aqua !important">
    <div>
        Hi,
    </div>
    <div>
        this MVC project has been done as an EZ exercise
    </div>
    <div>
        which is done with CRUD Methods
    </div>
    <div>
        1 to N Table Relations
    </div>
    <div>
        and We have the use of Enums too!!! <i style="color:red" class="far fa-grin-tongue-wink fa-2x"></i>
    </div>
    <hr />
    <div>
        Everyhing is done so with EF, I guess...
    </div>
    <div>
        but...
    </div>
    <div>
        Click <a href="https://www.ef.com/wwen/">HERE</a> to understand what is EF
    </div>
    <hr style="width:30% !important" />
    <div>
        This is a Professional Project
    </div>
    <div>
        so...
    </div>
    <div>
        if u want to criticize
    </div>
    <div>
        I give u an
    </div>
    <div>
        ...
    </div>
    <a href="https://www.wikihow.com/Uninstall-Windows">
        ADVICE
    </a>
    <hr style="width:10% !important" />
</div>
<div style="text-align:center; color:yellow">
    <h4 style="color:white"> <i style="color:red">!!! </i> <i class="fab fa-btc" style="color:rgb(8 208 34 / 0.95)"></i> COPYRIGHT NOT ADDED <i class="fab fa-btc" style="color:rgb(8 208 34 / 0.95)"></i> <i style="color:red"> !!!</i></h4>
</div>

CeLaFaremoMVC/Views/Laptop/Create.cshtml
@model CeLaFaremoMVC.Models.Laptop

@{
    ViewData["Title"] = "Laptop Create Form";
}
<h2 style="color:yellow ;text-align:center">ENTER THE DATA</h2>
<br />
<form method="post" asp-action="Create">
    <table class="table table-bordered table-striped" style="width:auto; margin-left: auto;margin-right: auto; width:35%">
        <tr>
            <td>
                <label asp-for="Id" style="color:red; text-align:center">Id</label>
                <input asp-for="Id" placeholder="Insert the ID" style="float: right; width: 60%;">
                <span asp-validation-for="Id"></span>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Brand" style="color:red; text-align:center">Brand</label>
                <input asp-for="Brand" placeholder="Brand Name..." style="float: right; width: 60%;">
                <span asp-validation-for="Brand"></span>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Modello" style="color:red; text-align:center">Model</label>
                <input asp-for="Modello" placeholder="Model.." style="float: right; width: 60%;">
                <span asp-validation-for="Modello"></span>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="RamMemory" style="color:red; text-align:center">Ram</label>
                <input asp-for="RamMemory" placeholder="Ram Qty in Gb..." style="float: right; width: 60%;">
                <span asp-validation-for="RamMemory"></span>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="SsdMemory" style="color:red; text-align:center">SSD</label>
                <input asp-for="SsdMemory" placeholder="SSD Memory Qty Mb..." style="float: right; width: 60%;">
                <span asp-validation-for="SsdMemory"></span>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="ElectronicId" style="color:red; text-align:center">ELECTRONIC ID</label>
                <input asp-for="ElectronicId" placeholder="ID of the Electronic Field" style="float:right; width:60%;">
                <span asp-validation-for="ElectronicId"></span>
            </td>
        </tr>
    </table>
    <div style="text-align:center">
        <input type="submit" value="Create" class="btn btn-danger" width="65" />
        <a asp-controller="Laptop" asp-action="Index" class="btn btn-success" style="margin-left:5px">Go Back</a>
    </div>
</form>

CeLaFaremoMVC/Views/Laptop/Delete.cshtml
@model CeLaFaremoMVC.Models.Laptop

@{
    ViewData["Title"] = "Delete Laptop";
}
<h2 style="color:yellow ;text-align:center">ARE YOU SURE???</h2>
<br />
<form method="post" asp-action="DeletePost" asp-route-Id="@Model.Id">
    <table class="table table-bordered table-striped" style="width:auto; margin-left: auto;margin-right: auto; width:35%">
        <tr>
            <td>
                <label asp-for="Id" style="color:red; text-align:center">Id</label>
                <input asp-for="Id" placeholder="Insert the ID" style="float: right; width: 60%;" disabled>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Brand" style="color:red; text-align:center">Brand</label>
                <input asp-for="Brand" placeholder="Brand Name..." style="float: right; width: 60%;" disabled>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Modello" style="color:red; text-align:center">Model</label>
                <input asp-for="Modello" placeholder="Model.." style="float: right; width: 60%;" disabled>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="RamMemory" style="color:red; text-align:center">Ram</label>
                <input asp-for="RamMemory" placeholder="Ram Qty in Gb..." style="float: right; width: 60%;" disabled>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="SsdMemory" style="color:red; text-align:center">SSD</label>
                <input asp-for="SsdMemory" placeholder="SSD Memory Qty Mb..." style="float: right; width: 60%;" disabled>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="ElectronicId" style="color:red; text-align:center">ELECTRONIC ID</label>
                <input asp-for="ElectronicId" placeholder="ID of the Electronic Field" style="float:right; width:60%;" disabled>
            </td>
        </tr>
    </table>
    <div style="text-align:center">
        <input type="submit" value="Delete" class="btn btn-danger" width="65" />
        <a asp-controller="Laptop" asp-action="Index" class="btn btn-success" style="margin-left:5px">Go Back</a>
    </div>
</form>

CeLaFaremoMVC/Views/Laptop/Index.cshtml
@model IEnumerable<CeLaFaremoMVC.Models.Laptop>

@using CeLaFaremoMVC.Enums 

@{
    ViewData["Title"] = "Laptop Index";
}

@*questo model count qui sotto ci serve per dire che se abbiamo piu di 0 elementi da mostrare
    li faremo vedere
    altrimenti diremo che non abbiamo nulla in questa pagina, in modo specifico non abbiamo
    cose nella tabella di questo db*@
@if (Model.Count() > 0)
{
    <h1 style="text-align:center">LAPTOP LIST</h1>
    <br />
    <br />
    <div class="container">
        @*div => e' un divider*@
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                @*thead si usa per raggruppare il contenuto della head di una table*@
                <tr>
                    @*tr => e' un table row, quindi la riga di una tabella*@
                    <td id="headTextColor">
                        @*td => si usa per definire un data cell in a table*@
                        Id
                    </td>
                    <td id="headTextColor">
                        Brand
                    </td>
                    <td id="headTextColor">
                        Modello
                    </td>
                    <td id="headTextColor">
                        Ram Memory
                    </td>
                    <td id="headTextColor">
                        SSD Memory
                    </td>
                    <td id="headTextColor">
                        Category ID
                    </td>
                    <td id="headTextColor">
                        Modify or Delete
                    </td>
                </tr>
            </thead>
            <tbody>
                @*tbody si usa per inserire il contenuto del body in ua tabella*@
                @foreach (var laptops in Model)
                {
                <tr style="text-align:center">
                    <td>
                        @laptops.Id
                    </td>
                    <td>
                        @laptops.Brand
                    </td>
                    <td>
                        @laptops.Modello
                    </td>
                    <td>
                        @laptops.RamMemory Gb
                    </td>
                    <td>
                        @laptops.SsdMemory Mb
                    </td>
                    <td>
                        @laptops.ElectronicId
                    </td>
                    <td width="20%">
                        <div class="w-100 btn-group" role="group">
                            @*dato che si tratta di una lista, se devo prendere una proprieta' non posso usare il Model (che serve appunto a prendere le proprieta')
                ma devo ciclare la lista e prendermi la proprieta'*@
                            <a class="btn btn-success mx-1" asp-controller="Laptop" asp-action="Update" asp-route-Id="@laptops.Id">Modify</a>
                            <a class="btn btn-danger mx-1" asp-controller="Laptop" asp-action="Delete" asp-route-Id="@laptops.Id">Delete</a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <br />
    <div style="text-align:center">
        <h1>
            <i class="fas fa-chess-queen" style="color:greenyellow"></i>
            <a id="aHover" href="https://i.scdn.co/image/af2b8e57f6d7b5d43a616bd1e27ba552cd8bfd42">WARNING</a>
            <i class="fas fa-chess-queen" style="color:red"></i>
        </h1>
        <p>
            <h2>The Queen has stolen your List of Object</h2>
        </p>
        <h2>so...</h2>
        <p>
            <h3 style="color:yellow">there is no argument in this section!</h3>
        </p>
        <p>
            <h2>but...</h2>
        </p>
        <p>
            <h4 style="color:greenyellow">You can create a new Laptop,</h4>
        </p>
        <p>
            <h4 style="color:white">
                <i class="fas fa-hand-point-down" style="color:greenyellow"></i>
                click on the button below
                <i class="fas fa-hand-point-down" style="color:red"></i>
            </h4>
        </p>
    </div>
    <br />
}
<div style="text-align:center">
    <a id="btnCreate" asp-controller="Laptop" asp-action="Create" class="btn btn-success">Create a New Laptop</a>
</div>

CeLaFaremoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CeLaFaremoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" rel="stylesheet" />
</head>
<body style="background-color:#121533;">
    <header>
        <nav id="colorNavBar" class="navbar navbar-expand-sm">
            <a id="nameProjectBar" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <i id="leftFrog" class="fas fa-frog"></i>  SJPOWA-MVC-PROJECT  <i id="rightFrog" class="fas fa-frog"></i> </a>
                <ul class="navbar-nav flex-grow-1" style="margin-left:65%">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Electronic" asp-action="Index">ELECTRONICS</a>
                    </li>
                    <li class="nav-item"> 
                        <a class="nav-link" asp-area="" asp-controller="Laptop" asp-action="Index">LAPTOPS</a>
                    </li>
                </ul>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="footer" class="fixed-bottom">
        <div>
            <div>
                <h5 id="TopTextFooter">
                    SJPOWA SOCIALS
                </h5>
            </div>
            <div style="text-align:center">
                <a id="twitch" class="fab fa-twitch fa-2x mx-1" href="https://www.twitch.tv/sjpowa_"></a>
                <a id="youtube" class="fab fa-youtube fa-2x mx-1" href="https://www.youtube.com/channel/UCHxwpZzynNKeAaCiPVzlaWA"></a>
                <a id="instagram" class="fab fa-instagram fa-2x mx-1" href="https://www.instagram.com/sjpowa/?hl=en"></a>
            </div>
            <div>
                <a id="privacy" href="https://www.cia.gov/">Privacy</a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>